### ISSUE TITLE
Rollup Functions returning 0 for all but Count

### ISSUE THREAD

**Issue by davidbrooker** [demianrasko/Dynamics-365-Workflow-Tools#177] opened 2020-01-24 15:54 UTC
Workflow Tools 1.0.58.0 Dynamics 365 Online 9.1

Trying to use the workflow tools to produce Rollup fields. 

All functions are returning 0 (Zero) with the exception of the Count function which correctly returns the number of child records. The fields providing the "feeder" values are Simple whole number types. 

Crucially, I have managed to get the Opportunities > Accounts > Estimated Value example provided by Demian Rasko to work correctly in my installation. The workflow functions are also working OK with another example using custom entities that I have created. But the example I really want to work (the others are just tests) just keeps on returning all Zero (0) values with the exception of the Count function. 

The differences is that the working examples are using Currency fields to feed in the  values that are being rolled up whilst the one that will not work is using Whole Number fields. Also, the feeder records for the non working example has a large number of fields with a Zero (0) value in them (but no blanks)

So, Demian Rasko's workflow utility is almost certainly working OK and its probably my XML that is the problem. I have the following questions:

1. Should the Rollup functions work with Whole Number fields?

2. Can I ask what is the purpose of the parameter called _uitype="new_printcontract"_ in my XML? I have found that changing this to either the Parent or Child entity makes no diference to what the XML returns?

3. Can the workflow utilities handle Zero values in the feeder fields?

4. Can anyone spot anything obvious I have got wrong with my XML or have any suggestions?

The XML being used on the non-working example is shown below:

![image](https://user-images.githubusercontent.com/15276474/73082416-59894500-3ec1-11ea-8bf6-5c65dd129293.png)

Thanks

**Comment by TarogStar** [comment] 2020-02-05 22:49
We are hitting this too.  The code is checking only for decimal or money, not for integer (which is whole number) so it doesn't work for that.  It should be an easy fix, I'll see if there isn't already a pull request for that and help to get it fixed if not.

**Comment by davidbrooker** [comment] 2020-02-06 09:45
TarogStar,

Thanks for the response. So I think your saying that my XML is probably OK and its the workflow that seems to not deal with Integers (Whole Numbers) correctly? 

It would be good to get clarification for anybody later that comes along.

**Comment by DmitriRiz** [comment] 2020-02-28 17:10
The problem is that the aggregate functions do something funky if the data type is Whole Number. They work fine for currencies or decimals. 
So hopefully there's be a fix for this super-helpful action! Workaround for now could be to have a calculated decimal field that would contain a copy of whole number.

**Comment by demianrasko** [comment] 2020-07-12 15:26
Hi all, solved by @TarogStar Pull request: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/pull/181 and available in the new version 1.0.59.0

**Closed by demianrasko** 2020-07-12 15:26 UTC
