### ISSUE TITLE
The solution file is invalid.

### ISSUE THREAD

**Issue by donalmc** [demianrasko/Dynamics-365-Workflow-Tools#1] opened 2017-04-03 14:47 UTC
Hi,

When I attempt to import the solution into our Dynamics 365 environment, I get an error message with the below text in it.
Thanks,
Donal

The solution file is invalid. The compressed file must contain the following at its root: solution.xml, 
customizations.xml, and [Content _ Types].xml. Customization files exported from previous versions of 
Microsoft Dynamics 365 are not supported.

**Comment by donalmc** [comment] 2017-04-03 14:56
I found the latest working version on Codeplex - maybe I did something stupid here?

Thanks

**Comment by demianrasko** [comment] 2017-04-03 17:14
Hi donalmc, I just tested, and works fine.
Please check if your CRM Version is the same version you have. there are 3 versions:
8.0: Dynamics CRM 2016
8.1: Dynamics CRM 2016 Update 1
8.2: Dynamics 365

Thanks,

**Comment by donalmc** [comment] 2017-04-05 10:51
Hi demianrasko,

Thanks for getting back to me. I got the version on Codeplex installed no problem.
When I look inside the zip available here, it does not seem to be structured as one would expect a Dynamics solution to be structured. 

Thanks,
Donal

**Comment by demianrasko** [comment] 2017-04-08 23:07
Please check again, I just uploaded a new version...please confirm if now works, to close the issue...

**Comment by trondjun** [comment] 2017-04-09 11:42
Hi, we just tried the new solution in an onpremises Dynamics 365 environment, and the solution upload fails.

**Comment by demianrasko** [comment] 2017-04-09 12:09
Hi trondjun, could you share with me the build number of your CRM envirnoment and file name you downloaded?
Send me please also if you have the error details you get

Thanks

**Comment by trondjun** [comment] 2017-04-09 12:30
Hi!

Thanx for you quick reply!

I downloaded the master branch of your latest build, and we also tried the 1.38 build from cineplex.
I was not able to get the latest build into crm at all, and the latest from codeplex failed.

do you have an prebuilt version of the one with fixes from yesterday? Maybe that is the issue?

We are running Dynamics CRM OnPremises :
versjon 1612 (8.2.0.749) (DB 8.2.0.749)

Thanx,
Trond

**Comment by demianrasko** [comment] 2017-04-09 13:15
Thanks!
I'll check that tonight...
Regards

**Comment by trondjun** [comment] 2017-04-09 13:44
Hi again!

This might actually be something on our installation.
Will let you know if this is an actual issue. We are not able to install any solutions / plugins at all.

Thanx
Trond

**Comment by demianrasko** [comment] 2017-04-09 15:23
Hi trondjun, I just tried in my D365 Onprem server, and works fine: 
![image](https://cloud.githubusercontent.com/assets/18124945/24838481/fcbc0962-1d48-11e7-837c-41f5ef2359de.png)
(I tested with this file: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/releases/download/1.0.38.0/Dynamics365WorkflowTools_1_0_38_1_8.2.zip)

If you cannot import any solution, then the issue is not in this solution, is on your server implementation.
Please check if the service "Microsoft Dynamics CRM Sandbox Processing Service" is running (another user has this issue this week: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/2 )
hope this helps!

regards

**Closed** 2017-07-16 20:32 UTC
Labels: question
